Drakkar-Software/OctoBot

bot.py
config/cst.py
evaluator/Social/Social_evaluator.py
evaluator/TA/TA_evaluator.py
evaluator/TA/momentum_evaluator.py
evaluator/evaluator.py
evaluator/evaluator_thread.py

[Evaluator] Manage indicator pertinence

---

README.md

[Doc] Installation on README

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Documentation PR

---

backtesting/backtesting_util.py
backtesting/strategy_optimizer/strategy_optimizer.py
evaluator/abstract_evaluator.py
evaluator/symbol_evaluator.py
interfaces/web/models/interface_settings.py
octobot.py
services/abstract_service.py
tools/config_manager.py
tools/notifications.py
tools/tentacle_manager/tentacle_util.py
trading/exchanges/exchange_dispatcher.py
trading/exchanges/exchange_symbol_data.py
trading/trader/orders_manager.py
trading/trader/trader.py
trading/trader/trades_manager.py

- Fix `is not None` and `is None` conditions
- Improvements of some loops with comprehensive python

Coding style improvements

---

services/abstract_service.py

#450 fixed services startup config check

---

wercker.yml

Signed-off-by: Herklos <herklos.dev@protonmail.com>

Configure wercker to deploy latest on dev

---

Dockerfile
wercker.yml

Fix wercker deploy

---

Dockerfile
start.py

No need to be only in docker environment anymore.
Octobot will perform this checks in any situations.

Remove docker option

---

Dockerfile
docs/install/linux_dependencies.sh
start.py
tools/commands.py
tools/tentacle_manager/tentacle_manager.py
tools/tentacle_manager/tentacle_util.py

#456 Implement persistent configuration
https://github.com/Drakkar-Software/OctoBot/wiki/With-Docker

[Docker] Implement persistent configuration

---

config/__init__.py
tests/unit_tests/trading_modes_tests/abstract_mode_creator_test.py
tests/unit_tests/trading_tests/test_exchange_market_status_fixer.py
trading/exchanges/abstract_exchange.py
trading/exchanges/exchange_dispatcher.py
trading/exchanges/exchange_manager.py
trading/exchanges/exchange_market_status_fixer.py
trading/exchanges/exchange_simulator/exchange_simulator.py
trading/exchanges/rest_exchanges/rest_exchange.py
trading/trader/modes/abstract_mode_creator.py

#474 Implement exchange market status fixer

#474 Implement exchange market status  fixer

---

.travis.yml
README.md
appveyor.yml
interfaces/trading_util.py
interfaces/web/models/dashboard.py
interfaces/web/templates/macros/tables.html
interfaces/web/templates/trades.html
tools/pretty_printer.py
trading/trader/order.py
trading/trader/trade.py
trading/trader/trades_manager.py

Refactor Trade classe - Python 3.7

---

config/config.py
start.py

Fix erase config file with errors

---

README.md
config/__init__.py
docs/CHANGELOG.md

Changelog for 0.2.4-beta
*Released date : December 30 2018*
#433 [Style] Fix code errors 
#446 added real trader resync on InsufficientFunds 
#448 added refresh_real_trader telegram command  
#450 fixed services startup config check 
#456 Implement docker configuration persistence 
#457 improved data collector and market view select UX
#461 fixed generic card bug with space containing names 
#474 Implement exchange market status fixer 
#475 removed trailing new line 
#477 added stack trace print on all relevant exceptions
#483 fixed multiple addition in classes list
#486 Refactor Trade class 
- Docker image ready
- Forced refresh telegram command
- Exchange market status fixer
- Update python version to python 3.7.2
- Fixed trading marge colors 
- Fixed binance api …

[RELEASE] octobot version 0.2.4

---

config/default_evaluator_config.json

Update and improve default evaluator config by a logic evaluators combination.

#494 [Evaluator Config] Improve default

---

config/__init__.py
launcher.py
setup.py

Goal : 
- pip install octobot-launcher
- executable `octobot-launcher` will start octobot installer

#502 [Setup] Update and improve setup.py

---

interfaces/web/models/configuration.py
services/abstract_service.py
services/gmail_service.py
services/reddit_service.py
services/service_creator.py
services/telegram_service.py
services/twitter_service.py
services/web_service.py
trading/exchanges/exchange_manager.py
trading/exchanges/rest_exchanges/rest_exchange.py
trading/exchanges/websockets_exchanges/implementations/binance_websocket.py

#505 added offline support for the whole bot and interfaces

---

backtesting/backtesting.py
dev_requirements.txt
interfaces/telegram/bot.py
interfaces/trading_util.py
interfaces/web/controllers/dashboard.py
interfaces/web/static/js/components/dashboard.js
tests/unit_tests/trading_tests/test_trades_manager.py
tools/notifications.py
tools/pretty_printer.py
trading/trader/trader.py
trading/trader/trades_manager.py

#506 added initial portfolio protitability

---

backtesting/strategy_optimizer/strategy_optimizer.py
interfaces/web/models/dashboard.py
interfaces/web/models/strategy_optimizer.py

#517 fixed strategy optimizer initialisation issues on more than one use

---

appveyor.yml

Fix appveyor release branch

---

Dockerfile
docs/install/linux_dependencies.sh

Update docker source image 
resolve #526

[Docker] Migrate to python:3.7.2-slim-stretch

---

config/__init__.py
interfaces/telegram/bot.py
interfaces/trading_util.py
interfaces/web/templates/components/config/editable_config.html
interfaces/web/templates/components/config/service_card.html
interfaces/web/templates/config.html
services/telegram_service.py

#533 added telegram usernames whitelist

---

docs/install/raspberry-pre-install.sh

from [https://gist.github.com/SeppPenner/6a5a30ebc8f79936fa136c524417761d](https://gist.github.com/SeppPenner/6a5a30ebc8f79936fa136c524417761d)

#536 updated raspberry python installation

---

octobot.py
services/abstract_service.py
services/reddit_service.py
services/service_creator.py
services/telegram_service.py
services/twitter_service.py
services/web_service.py
tools/commands.py

Migrate services to async

---

config/__init__.py
evaluator/__init__.py
evaluator/evaluator_matrix.py

Migrate evaluator matrix to dataclass
resolve #509

[Matrix] Migrate to dataclass

---

tests/unit_tests/trading_modes_tests/abstract_mode_creator_test.py
tests/unit_tests/trading_tests/test_sub_portfolio.py
tools/errors.py
trading/exchanges/exchange_market_status_fixer.py
trading/exchanges/exchange_simulator/exchange_simulator.py
trading/trader/modes/abstract_mode_creator.py
trading/trader/order.py
trading/trader/trader.py

Create order error and fixed tests warnings

---

backtesting/collector/data_collector.py
backtesting/collector/exchange_collector.py
tools/commands.py

Migrate datacollector to async
resolves #534

Migrate datacollector async

---

.travis.yml
dev_requirements.txt

- Improve testing time
- Add macos tests

Improve travis tests and add macos

---

.travis.yml

- Fix travis [coveralls](https://coveralls.io/github/Drakkar-Software/OctoBot?branch=dev) push broken since December.

Fix travis coveralls push

---

README.md

Now the proposed command starts OctoBot detached, in interactive mode and with a name.
And the most important : **with beta tag, not latest**

Update README docker command

---

Dockerfile
docs/install/linux_dependencies.sh

- Improve docker size (-110MB) and build time

Dockerfile improvements

---

appveyor.yml

- Implement travis test run modification to appveyor.

Improve appveyor test run

---

.travis.yml

- Macos release & deploy (resolves #553)
- Release checksum in CI logs (#550 #549)

Add macos release and checksum in logs

---

appveyor.yml

[CI] Add pip cache for appveyor

---

interfaces/web/__init__.py
octobot.py
services/notifier_service.py
services/telegram_service.py
services/twitter_service.py
tools/notifications.py
trading/trader/modes/abstract_mode_decider.py
trading/trader/order_notifier.py
trading/trader/trader.py

- Migrate notifications to async

[Notifications] Migrate to async

---

.travis.yml
setup.py

- Fix & improve travis release process

[CI] Fix CI release process

---

.travis.yml
config/__init__.py
setup.py

- Create a 0.2.5 release candidate
depends on #569

[Pre-Release] Create version 0.2.5a0

---

.travis.yml
appveyor.yml
config/__init__.py

- Fix some deployment issues
- Add checksum for appveyor
resolves #549 
resolves #550

Fix travis deploy

---

tools/commands.py

Fix octobot restart

---

README.md

[![Downloads](https://pepy.tech/badge/octobot/month)](https://pepy.tech/project/octobot)

Add pypi download per month

---

interfaces/web/templates/footer.html

#572 added donation addresses

---

tools/notifications.py

- Fix exception handled during notify all.

[Bug] Fix notify all when no twitter service

---

trading/exchanges/exchange_dispatcher.py
trading/trader/trades_manager.py

#596 now won't spam "can't get matching symbol"

---

services/abstract_service.py
services/service_creator.py
services/telegram_service.py
services/web_service.py

#609 fixed telegram wrong warning

---

README.md
config/__init__.py
docs/CHANGELOG.md

to update changelog till release

updated changelog

---

pre_requirements.txt

Related to https://github.com/Drakkar-Software/OctoBot-Binary/pull/1

Fix pre_requirements for binary

---

pre_requirements.txt

Remove pandas from pre_requirements

Remove pandas

---

tests/unit_tests/trading_tests/test_orders_manager.py
trading/trader/order.py
trading/trader/orders_manager.py
trading/trader/portfolio.py

More than one stop in real trader

---

.travis.yml
README.md
setup.py

Fix setup.py

---

README.md
config/__init__.py
docs/CHANGELOG.md

[Version] 0.3.1

---

.travis.yml
README.md
config/__init__.py
docs/CHANGELOG.md
interfaces/web/api/metadata.py
pre_requirements.txt
requirements.txt
setup.py
tests/unit_tests/trading_modes_tests/abstract_mode_creator_test.py
tests/unit_tests/trading_tests/test_orders_manager.py
tools/external_resources_manager.py
tools/tentacle_manager/tentacle_manager.py
trading/trader/modes/abstract_mode_creator.py
trading/trader/order.py
trading/trader/orders_manager.py
trading/trader/portfolio.py

Changelog for 0.3.1-beta
*Released date : January 29 2019*
**Warning** :
- Version 0.3.0 required to reinstall all default tentacles (start.py -p reset_tentacles && start.py -p install all)
#624 fixed offline announcements
#629 fixed real trader multiple stop orders
#631 fixed dusts management round system
- Requirement cleanup    
- Fix pip delivery
- Fix real trader stop orders
- Fix dusts management
- Minor fixes on portfolio

[Release] Version 0.3.1

---

interfaces/web/web_app.py

- Starting performance improvement
- Close & restart properly

[Web Interface] Improve performance by using a dedicated server

---

config/__init__.py
interfaces/bots/interface_bot.py
interfaces/bots/telegram/bot.py
interfaces/trading_util.py
tests/static/config.json
tests/unit_tests/tools_tests/test_config_manager.py
tests/unit_tests/tools_tests/test_dict_util.py
tests/unit_tests/trading_modes_tests/abstract_mode_creator_test.py
tests/unit_tests/trading_tests/test_trader.py
tests/unit_tests/trading_tests/test_trades_manager.py
tools/config_manager.py
tools/dict_util.py
tools/pretty_printer.py
trading/trader/modes/abstract_mode_creator.py
trading/trader/modes/abstract_mode_decider.py
trading/trader/trader.py
trading/trader/trades_manager.py

#638 added bot commands

---

.travis.yml

With manual reconfigure some CI : 
Don't think there is something else to configure.

Migrate from beta branch to master

---

interfaces/trading_util.py
interfaces/web/advanced_controllers/matrix.py
interfaces/web/advanced_templates/advanced_layout.html
interfaces/web/advanced_templates/advanced_matrix.html

[Advanced Web interface] Create matrix view

---

trading/trader/order.py
trading/trader/trade.py
trading/trader/trader.py

This PR concerns Order class.
Done for Trade class in https://github.com/Drakkar-Software/OctoBot/pull/487.
resolves #486

[Python3.7] Refactor Order and Trade classes

---

config/__init__.py
interfaces/bots/__init__.py
interfaces/bots/interface_bot.py
interfaces/bots/telegram/bot.py
interfaces/trading_util.py
services/telegram_service.py
tools/notifications.py
tools/pretty_printer.py
trading/trader/trader.py

todo: refresh telegram notifications

#671 refreshed telegram interface using markdown

---

interfaces/web/static/js/common/candlesticks.js

#687 improved readability

---

interfaces/trading_util.py
interfaces/web/templates/macros/tables.html
tests/unit_tests/trading_tests/test_trader.py
trading/exchanges/websockets_exchanges/implementations/binance_websocket.py
trading/trader/order.py
trading/trader/trade.py
trading/trader/trader.py

#686 fixed market order costs on ws

---

config/__init__.py
interfaces/web/controllers/configuration.py
interfaces/web/models/configuration.py
interfaces/web/static/js/components/data_collector.js
interfaces/web/templates/config.html

#700 now display exchanges in select groups

---

interfaces/web/static/css/style.css
interfaces/web/static/js/components/interface_settings.js
interfaces/web/templates/backtesting.html
interfaces/web/templates/symbol_market_status.html

improved config modified item color and fixed market status bug

---

config/__init__.py
evaluator/Strategies/strategies_evaluator.py
evaluator/Updaters/global_price_updater.py
evaluator/evaluator.py
evaluator/evaluator_task_manager.py
evaluator/symbol_evaluator.py
interfaces/web/models/configuration.py
interfaces/web/models/dashboard.py
interfaces/web/static/js/components/interface_settings.js
interfaces/web/templates/trading.html
octobot.py
tests/unit_tests/trading_modes_tests/abstract_mode_creator_test.py
tools/time_frame_manager.py
trading/exchanges/exchange_manager.py
trading/exchanges/rest_exchanges/rest_exchange.py
trading/trader/modes/abstract_mode_creator.py
trading/trader/modes/abstract_mode_decider.py
trading/trader/modes/abstract_trading_mode.py
trading/trader/order.py
trading/trader/orders_manager.py
trading/trader/trader.py

see https://github.com/Drakkar-Software/OctoBot-Tentacles/issues/28

prepare for staggered orders strategy

---

trading/trader/order.py
trading/trader/trades_manager.py

#713 fixed /fees command error on stop loss orders

---

start.py
tools/__init__.py

improved python version check

---

evaluator/Strategies/strategies_evaluator.py
tests/test_utils/data_bank.py
tools/dict_util.py
trading/exchanges/exchange_simulator/exchange_simulator.py
trading/trader/modes/abstract_trading_mode.py

Refactor code style :
```
var = var if var is not None else "default"
```
to 
```
var = var or "default"
```

[Code cleanup] Refactor code assignation with None check

---

evaluator/Util/advanced_manager.py

Add a warning when duplicate tentacle names

Add a warning when duplicate tentacle names

---

interfaces/web/templates/footer.html

added telegram community link

---

config/__init__.py

might fix
https://github.com/Drakkar-Software/OctoBot/issues/740

#740 attempts to fix timeout user issue

---

trading/trader/modes/abstract_trading_mode.py
trading/trader/trader.py

required by https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/51

added utility methods

---

trading/trader/trader.py

required by https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/56

added reference market getter from trader

---

interfaces/trading_util.py
interfaces/web/api/trading.py
interfaces/web/static/js/components/trading.js
interfaces/web/templates/trading.html
trading/trader/trader.py

add filter on cancel orders

---

docs/install/arm32v7/Dockerfile

https://hub.docker.com/r/drakkarsoftware/octobot-pi

[Docker] Raspberry image

---

interfaces/web/static/js/components/trading.js
interfaces/web/templates/trading.html

added cancel orders progress bar

---

interfaces/web/controllers/configuration.py
services/abstract_service.py
services/telegram_service.py
services/web_service.py
start.py

Improve telegram start

---

interfaces/web/advanced_templates/advanced_evaluator_config.html
interfaces/web/advanced_templates/advanced_index.html
interfaces/web/advanced_templates/advanced_layout.html
interfaces/web/advanced_templates/advanced_matrix.html
interfaces/web/advanced_templates/advanced_strategy_optimizer.html
interfaces/web/static/css/style.css
interfaces/web/templates/backtesting.html
interfaces/web/templates/commands.html
interfaces/web/templates/community.html
interfaces/web/templates/config.html
interfaces/web/templates/data_collector.html
interfaces/web/templates/index.html
interfaces/web/templates/layout.html
interfaces/web/templates/logs.html
interfaces/web/templates/portfolio.html
interfaces/web/templates/symbol_market_status.html
interfaces/web/templates/tentacle_packages.html
interfaces/web/templates/tentacles.html
interfaces/web/templates/trades.html
interfaces/web/templates/trading.html

here home is selected, what do you think @Herklos ?

Navbar current selection UX improvement

---

trading/trader/modes/abstract_trading_mode.py

previously:
* bot did not start and crashed instead

#832 now start with error log if trading mode can't init

---

core/evaluator_factory.py
trading/exchanges/exchange_manager.py

trading pair and timeframe error message

---

config/__init__.py
interfaces/web/templates/components/config/exchange_card.html
tools/config_manager.py
trading/exchanges/abstract_exchange.py
trading/exchanges/exchange_dispatcher.py
trading/exchanges/exchange_personal_data.py
trading/exchanges/rest_exchanges/rest_exchange.py

Added exchanges api passwords handling

---

backtesting/collector/data_file_manager.py
interfaces/web/templates/backtesting.html
interfaces/web/templates/data_collector.html

#839 improved backtesting files display

---

config/__init__.py
config/config_schema.json
config/default_config.json
config/disclaimer.py
interfaces/web/controllers/commands.py
interfaces/web/controllers/terms.py
interfaces/web/models/configuration.py
interfaces/web/static/js/components/commands.js
interfaces/web/templates/commands.html
interfaces/web/templates/layout.html
interfaces/web/templates/macros/text.html
interfaces/web/templates/terms.html
start.py
tools/config_manager.py

#847 added disclaimer as terms

---

README.md

[![Active OctoBot](https://img.shields.io/badge/OctoBots%20online%20this%20month-90-green.svg)]()

[README] introduce active bots counter badge

---

README.md

[![Active OctoBot](https://img.shields.io/badge/dynamic/json.svg?&url=https://octobotmetrics.herokuapp.com/metrics/community/count/0/-1/0&query=$.total&color=green&label=OctoBots%20online%20this%20month)]()

Update badge month counter

---

interfaces/web/templates/commands.html
interfaces/web/templates/components/config/editable_config.html
interfaces/web/templates/components/config/exchange_card.html

text input 
* don't reset when out focused
* trigger bold on edited fields
bool input use switches:

Improved text and checkboxes input UI

---

interfaces/web/controllers/configuration.py
interfaces/web/static/js/common/cst.js
interfaces/web/static/js/common/dom_updater.js
interfaces/web/static/js/components/configuration.js
interfaces/web/templates/config.html
tools/config_manager.py

Do not allow simulator and real trader simultaneously

---

interfaces/web/static/js/common/util.js
interfaces/web/static/js/components/config_tentacle.js
interfaces/web/templates/config_tentacle.html

requires https://github.com/Drakkar-Software/OctoBot/pull/880 for js constant "modified_badge"

added exit confirm on tentacle config modification

---

config/__init__.py

increased community tops count

---

interfaces/web/static/js/common/util.js
interfaces/web/static/js/components/config_tentacle.js

fixed never deactivated exit confirm box and web interface number repr

---

interfaces/web/static/js/common/util.js

#896 fixed decimal display

---

trading/exchanges/exchange_symbol_data.py

#901 fixed attribute error and added error message

---

trading/trader/orders_manager.py
trading/trader/portfolio.py
trading/trader/trader.py

required by staggered orders and probably many future strategies

added recently closed orders handling

---

interfaces/web/models/dashboard.py
tests/unit_tests/core_tests/evaluator_factory_test.py
tests/unit_tests/trading_tests/test_exchange_manager.py
trading/exchanges/exchange_manager.py

Fix Config checker failed when using wildcard on pairs #900

---

interfaces/web/templates/components/config/exchange_card.html
trading/exchanges/rest_exchanges/rest_exchange.py

I also improved the exchange card interface to separate the password part

#937 fixed error with api-password

---

evaluator/Updaters/global_price_updater.py

closes #940
Example in 1m time frame:
Before
(Always refreshed at XX:XX:32)
After
(First refresh at stratup and then always refreshed at XX:XX:00)

Fix candle updater synchronization

---

interfaces/web/static/js/common/json_editor_settings.js
interfaces/web/templates/config.html
tools/dict_util.py

(from daily trading mode config interface https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/78)

added switch design for tentacle config checkboxes

---

interfaces/web/templates/layout.html

swapped config and backtesting in navbar

---

README.md
config/__init__.py
docs/CHANGELOG.md

Changelog for 0.3.6-beta
*Released date : July 15 2019*
#922 [Notifications] Uncaught exception when error on notifications publish bug
#937 [Exchanges] API token fail when api-password is provided but not necessary bug
#940 [Bug][High] Fix updater candle time synchronization
#927 [Docker] expose web interface for inter-container communications
#900 Fix Config checker failed when using wildcard on pairs
#931 Improved navbar UI
#944 Added switch design for tentacle config checkboxes
- Fixed exchange API token error during first installation
- Fixed timeframes update rate to fit timeframes time
- Fixed uncaught notification exception
- Fixed wildcard configuration validation error
- Added configuration for Daily and Signal trading modes
- Improved web interface UI

version 0.3.6

---

.gitignore
config/__init__.py
config/config.py
tools/config_manager.py

To improve docker running command.
New starting docker command : 
```
docker run -it -d --name MyAmazingOctobot -v $(pwd)/user:/bot/octobot/user -v $(pwd)/logs:/bot/octobot/logs -v $(pwd)/tentacles:/bot/octobot/tentacles drakkarsoftware/octobot:beta
```
closes #949

Migrate config file to user folder #949

---

.dockerignore
Dockerfile

[Docker] improve dockerfile

---

evaluator/Updaters/global_price_updater.py
trading/exchanges/exchange_simulator/exchange_simulator.py

fix regression from update after Drakkar-Software/OctoBot#958

#960 compute backtesting profitability on the last candle

---

trading/exchanges/exchange_simulator/exchange_simulator.py

Very old problem but this fields is very rarely used, except with dip analyser

#964 fix exchange simulator too high minimum price

---

trading/trader/trades_manager.py

Now consider every pairs when computing portfolio total value and when a ticker price is 0: tries inverted ticker (true for binance stable coins)
before:
after:

#962 fix portfolio evaluation with multiple pairs

---

interfaces/web/api/trading.py
interfaces/web/controllers/trading.py
interfaces/web/static/js/components/trading.js
interfaces/web/templates/trading.html

Button appearing only if a real trader is running:

#969 add real trader refresh in web interface

---

README.md
config/__init__.py
docs/CHANGELOG.md

Changelog for 0.3.7-beta
*Released date : August 31 2019*
#948 [Trading] Add 6h timeframe
#949 [Config] Migrate config file to user folder enhancement
#952 [Trader] Fix kraken orders
#953 [Docker] Improve dockerfile
#955 [Backtesting] Improve recent trades generation
#960 [Backtesting] Use the last candle for profitability computation
#962 [Portfolio] Missing stablecoins in traded portfolio
#964 [Backtesting][DipAnalyser] try to create sell order without enough funds
#968 [Web interface] Handle errors 
#969 [Web interface] Add refresh real trader button
- Fixed errors when creating orders on Kraken exchange
- Fixed innacuracies in backtesting
- Now correctly takes every currency into consideration when computing profitability and holdings
- Fixed backtesting exchange …

[Release] Version 0.3.7

---

requirements.txt

bug to be fixed: https://github.com/sammchardy/python-binance/issues/449

remove 0.7.4 python binance version due to regression

---

config/__init__.py
trading/trader/order.py
trading/trader/trader.py

add new exchange order types support

---

trading/exchanges/rest_exchanges/rest_exchange.py

Removed with https://github.com/ccxt/ccxt/commit/347a3981debd31fd31ea36a82915f3e643b607f6

Fixed ccxt removed find_market method

---

.travis.yml
README.md
appveyor.yml
backtesting/collector/data_parser.py
config/__init__.py
config/local_rotating_file_handler.py
config/logging_config.ini
docs/CHANGELOG.md
docs/install/arm32v7/Dockerfile
docs/install/linux_installer.sh
docs/install/windows_installer.bat
evaluator/Updaters/global_price_updater.py
requirements.txt
start.py
tools/__init__.py
trading/exchanges/rest_exchanges/rest_exchange.py
trading/trader/order.py
trading/trader/trader.py

Changelog for 0.3.8-beta
*Released date : December 28 2019*
#978 can now call start.py from any directory
#991 add new exchange order types support
- Fixed ccxt deprecated methods
- Fixed binance websocket regression
- Start can now be started from any directory
- New order types support

[Release] v0.3.8

---

octobot/evaluator_factory.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/60

[EvaluatorFactory] Use new exchanges get all method

---

octobot/evaluator_factory.pxd
octobot/evaluator_factory.py

Requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/13 and https://github.com/Drakkar-Software/OctoBot-Trading/pull/56
Related to https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/12#discussion_r362324310

[EvaluatorFactory] Add cryptocurrency support

---

tools/logger.py

Depends on Drakkar-Software/OctoBot-Evaluators#19

[Matrix] migrate matrix callback

---

octobot/initializer.pxd
octobot/task_manager.py
tools/config_manager.py
tools/metrics/__init__.py
tools/metrics/metrics_analysis.py
tools/metrics/metrics_fields.py
tools/metrics/metrics_manager.py

requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/9
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/30
requires https://github.com/Drakkar-Software/OctoBot/pull/1009
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/68

Add metrics management

---

octobot/exchange_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/69

add ignore config param in exchange factory

---

octobot/evaluator_factory.pxd
octobot/evaluator_factory.py
requirements.txt
tools/logger.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/18

[Evaluator] Add matrix id management 

---

octobot/exchange_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/75

[ExchangeFactory] Add matrix id

---

octobot/exchange_factory.py
tools/logger.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/71

[ExchangeChannel] Add exchange id

---

octobot/exchange_factory.py

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/72

[ExchangeFactory] Migrate to exchange builder 

---

octobot/exchange_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/14

restore backtesting start argument

---

octobot/interface_factory.py
octobot/service_feed_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Interfaces/pull/16
requires https://github.com/Drakkar-Software/OctoBot-Services/pull/8

do not create all interfaces and feeds in backtesting

---

octobot/evaluator_factory.py
tools/metrics/metrics_manager.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/33

Fix evaluators wildcard usage

---

tools/logger.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/110

update trade and order callbacks

---

tools/commands.py
tools/config_manager.py
tools/metrics/metrics_manager.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/19

update exception logger

---

config/__init__.py
interfaces/web/models/configuration.py
interfaces/web/templates/config.html

use api.coincap.io for currency list 

---

.gitignore
config/__init__.py
config/default_tentacles_config.json
config/default_trading_config.json
octobot/configuration_manager.pxd
octobot/configuration_manager.py
octobot/evaluator_factory.py
octobot/exchange_factory.py
octobot/initializer.py
octobot/octobot.py
octobot/octobot_api.py
requirements.txt
setup.py
start.py
tools/__init__.py
tools/commands.py
tools/logger.py
tools/metrics/metrics_manager.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/28
When merged, to export local tentacles to an exisiting tentacles repo:
```bash
python start.py tentacles -e "/X/Y/Z/OctoBot-tentacles" -d ./tentacles
```

Package manager refactor 

---

requirements.txt

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/150

[Logger] Fix import error 

---

CHANGELOG.md
README.md
config/__init__.py
octobot/exchange_factory.py
requirements.txt
tests/unit_tests/evaluator_tests/test_evaluator_creator.py
tests/unit_tests/evaluator_tests/test_evaluator_task_manager.py
tests/unit_tests/evaluator_tests/test_symbol_evaluator.py
tools/logger.py

Fix wildcard imports

---

CHANGELOG.md
README.md
config/__init__.py
requirements.txt

- Tentacles cythonization
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/157
Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/36

Remove tentacles cythonization 

---

octobot/commands.py
octobot/factories/evaluator_factory.py
octobot/factories/service_feed_factory.py
octobot/octobot.pxd
octobot/octobot.py
start.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/18
requires https://github.com/Drakkar-Software/OctoBot-Services/pull/14
requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/42

Tentacles migration adaptations 

---

CHANGELOG.md
README.md
octobot/constants.py
octobot/task_manager.pxd
octobot/task_manager.py
requirements.txt

- Create config when missing user folder
- bot_id generation
- Python files organisation refactor
- Metrics to community
- Script helper

[Version] v0.4.0-alpha8

---

start.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/46

[Start] Import commons ConfigEvaluatorError

---

CHANGELOG.md
README.md
octobot/constants.py
requirements.txt

- [Start] Import ConfigEvaluatorError from OctoBot-Commons
- [Stop] recursion error
-  octobot_api cython headers

[Version] v0.4.0-alpha9

---

octobot/factories/evaluator_factory.py
octobot/logger.py
requirements.txt
tests/functional_tests/strategy_evaluators_tests/abstract_strategy_test.py

Depends on https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/52

[Evaluators] Adapt evaluator get_chan with matrix_id 

---

Dockerfile

- Fix arm arch missing libffi-dev and libssl-dev packages
- Create an octobot user to improve security

[Dockerfile] Update

---

octobot/logger.py

Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/57

Fix OctoBot-Commons updates 

---

README.md

Replace code factor by codacy badge

---

octobot/community/community_manager.py
octobot/factories/interface_factory.py
octobot/octobot.py
octobot/task_manager.py
requirements.txt
start.py

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/27

migrate interfaces and notifications into services

---

octobot/factories/exchange_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/177

set bot_id in exchange builder

---

octobot/backtesting/octobot_backtesting.py
octobot/factories/interface_factory.py
octobot/factories/service_feed_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/31

allow services to update config

---

octobot/commands.py
octobot/initializer.py
requirements.txt
tests/test_utils/bot_management.py
tests/test_utils/config.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/32

use sync files IO for tentacles operations

---

octobot/api/backtesting.py
octobot/backtesting/independent_backtesting.py
octobot/backtesting/octobot_backtesting.py
requirements.txt
tests/functional_tests/backtesting_tests/backtesting_test.py
tests/functional_tests/strategy_evaluators_tests/abstract_strategy_test.py
tests/static/default_tentacles_config.json
tests/test_utils/bot_management.py
tests/test_utils/config.py
tests/test_utils/data_bank.py
tests/test_utils/memory_check_util.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/66
requires https://github.com/Drakkar-Software/OctoBot/pull/1154

fix memory check and add tentacle memory check util function

---

octobot/backtesting/independent_backtesting.py
octobot/backtesting/octobot_backtesting_factory.py

fixes https://github.com/Drakkar-Software/OctoBot/issues/1159

log error message on missing data files

---

start.py

[Start] Remove datacollector

---

octobot/backtesting/abstract_backtesting_test.py
tests/functional_tests/strategy_evaluators_tests/abstract_strategy_test.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/188
requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/68
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/34
now trades on time

fix strategy test framework

---

octobot/api/backtesting.py
octobot/backtesting/independent_backtesting.pxd
octobot/backtesting/independent_backtesting.py
octobot/backtesting/octobot_backtesting_factory.pxd
octobot/backtesting/octobot_backtesting_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/70

add backtesting log report

---

octobot/factories/exchange_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/197

add sandboxed and enabled config for exchanges

---

setup.py

Thank you for sending your pull request.
But first, have you included unit tests, and is your code PEP8 conformant? More details
Summary
This should fix Pypi description page visuzlization
Changelog
What's new?
Explain in details what this PR solve or improve.

Update setup.py with fix for Pypi

---

Dockerfile
octobot/cli.py
setup.py

- PIP package tentacles imports
- Docker tentacles persistence

Fix pip package

---

octobot/cli.py

log current environment at startup

---

octobot/consumers/octobot_channel_consumer.py
octobot/producers/interface_producer.pxd
octobot/producers/interface_producer.py
octobot/producers/service_feed_producer.pxd
octobot/producers/service_feed_producer.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/44

handle channel services creation

---

octobot/backtesting/independent_backtesting.py
octobot/backtesting/octobot_backtesting.py
octobot/community/community_manager.py
octobot/config/default_config.json
octobot/producers/evaluator_producer.py
octobot/producers/exchange_producer.py
octobot/strategy_optimizer/strategy_optimizer.py

requires https://github.com/Drakkar-Software/OctoBot/pull/1206
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/88

Remove advanced manager

---

azure-pipelines.yml
requirements.txt
tests/unit_tests/trading_modes_tests/trading_mode_test_toolkit.py

require https://github.com/Drakkar-Software/OctoBot-Trading/pull/229
require https://github.com/Drakkar-Software/OctoBot-Services/pull/47

update order close method in tests

---

docker-compose.yml

Used by https://github.com/Drakkar-Software/OctoBot/wiki/With-Docker#running-with-docker-compose

[Docker] Add docker-compose.yml

---

octobot/commands.py
requirements.txt
setup.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/44

add bot install dir into tentacles manager cli

---

octobot/cli.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/45

use tentacles manager strict tentacles check

---

octobot/backtesting/independent_backtesting.pxd
octobot/backtesting/independent_backtesting.py
octobot/backtesting/octobot_backtesting.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/88

release database file after backtesting

---

requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/92
requires https://github.com/Drakkar-Software/OctoBot-Services/pull/49

update requirements for web interface login

---

requirements.txt
tests/unit_tests/trading_modes_tests/trading_mode_test_toolkit.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/247
requires https://github.com/Drakkar-Software/OctoBot-Services/pull/50

Fix tentacles tests

---

requirements.txt
setup.py

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/279

[Requirements] Update

---

requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/51

bump tentacles requirement

---

CHANGELOG.md
README.md
octobot/constants.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/58

bump requirements

---

CHANGELOG.md
README.md
octobot/constants.py
octobot/logger.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/60

[Version] v0.4.0-alpha23

---

.travis.yml

Partially replaced by https://github.com/Drakkar-Software/OctoBot/pull/1310
We should also find another way to have a public demo (on heroku the WS can't connect).

[CI] Remove heroku deployment

---

octobot/backtesting/octobot_backtesting.py

Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/344

[Backtesting] Fix import

---

.gitignore
octobot/constants.py
octobot/logger.py

Goal: be able to easily change the logging config
requires https://github.com/Drakkar-Software/OctoBot/pull/1343

Use local logging config

---

tests/test_utils/memory_check_util.py

add post_backtesting_task await in memory checks

---

octobot/config/config_schema.json
octobot/config/default_config.json

used by https://github.com/Drakkar-Software/OctoBot-Trading/pull/434

add load-trade-history in config

---

README.md

👋  just noticed you are trying out the Deploy to DigitalOcean button! Thanks for trying it out and do let us know if you have any feedback!

README.md: fixed misspelling

---

.github/workflows/main.yml
CHANGELOG.md
README.md
octobot/channels/octobot_channel.py
octobot/constants.py
requirements.txt

ex of log:
2020-12-06 22:19:51,387 DEBUG    OctoBotChannel       Consumer started for subject: notification action: exchange [OctoBotChannelConsumer with callback: _exchange_added_callback]

now log on new consumer on octobot channel

---

Dockerfile
docker-compose.yml

- Dockerfile with new default volumes
- docker-compose.yml with default http port and new default volumes

[Docker] Update Dockerfile and docker-compose.yml

---

octobot/producers/interface_producer.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/85

send executor to notifiers

---

.do/deploy.template.yaml

use master in digital ocean deployment

---

.github/workflows/main.yml

[CI] Add docker run and check health

---

requirements.txt

Depends on https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/94

[Requirement] Update TentaclesManager

---

.github/workflows/main.yml

Uses pull_request according to https://securitylab.github.com/research/github-actions-preventing-pwn-requests to run jobs securely

[CI] Enable fork to create PR and have CI running

---

.github/workflows/analyze.yml

Recommended by github in https://github.com/Drakkar-Software/OctoBot/security/code-scanning

[CI] Add codeql workflow

---

docs/source/pages/Configuration.rst
docs/source/pages/Contribution.rst

restore https://github.com/Drakkar-Software/OctoBot/pull/1492

[Docs] Update configuration

---

.github/workflows/doc.yml
requirements.txt

Inspired from https://github.com/sopel-irc/docker-sopel/issues/37 temporary fix
We should remove this fix when https://github.com/aio-libs/aiohttp/issues/5366 is resolved

[Requirements] Temporary fix aiohttp install issue

---

CHANGELOG.md
README.md
octobot/configuration_manager.py
octobot/constants.py
requirements.txt

Bump version

---

docs/source/pages/Exchanges.rst

[Docs] Update Exchanges page

---

docker-compose.yml
docs/source/pages/With-Docker.rst

[Docker] Add ssl support

---

CHANGELOG.md
README.md
octobot/constants.py
requirements.txt
setup.py

- Web interface
- Exchange issues (binance and kraken)

[Version] v0.4.0b5

---

.github/workflows/doc.yml
Dockerfile
requirements.txt
setup.py

[Requirements] Update aiohttp with chardet bump

---

docs/source/pages/With-Python-only.rst

[Docs] Add python source install screen usage

---

docs/source/pages/Web-interface.rst

[Docs] Add simple steps to configure web password

---

docs/source/_templates/layout.html
docs/source/_templates/theme_variables.jinja

[Docs] Add feedback link

---

CHANGELOG.md
README.md
octobot/constants.py
requirements.txt

Fixes https://github.com/Drakkar-Software/OctoBot/issues/1579
- GridOrders config check
- Symbol wildcard configuration
- Docker raspberry armv7 image (thanks to @gabriel-milan)

[Version] v0.4.0b7

---

docs/source/pages/Trader.rst

[Docs] Add Load-Trade-History in Trader

---

tests/unit_tests/community/__init__.py
tests/unit_tests/community/test_community_data.py

Add test to prevent OctoBot-Commons v1.5.12 bug from happening

[Tests] Add community data

---

docs/source/index.rst
docs/source/pages/Contribution.rst
docs/source/pages/Customize-your-OctoBot.rst
docs/source/pages/Developer-Guide.rst
docs/source/pages/For-Developers.rst
docs/source/pages/Tentacle-Development.rst
docs/source/pages/Tentacle-Package-Development.rst
docs/source/pages/Web-interface.rst
docs/source/pages/With-Docker-on-Android.rst
docs/source/pages/With-Python-only.rst

[Docs] Add tentacle package development

---

okteto-stack.yaml

https://octobot-herklos.cloud.okteto.net/home

Fix okteto-stack.yaml resources

---

octobot/constants.py
octobot/logger.py

Required to prevent spam with websockets

[Loggers] Disable DEBUG logs by default. Reactivable with ENV var

---

octobot/community/community_analysis.py
requirements.txt

requires OctoBot-Trading==1.12.16

Bump trading

---

octobot/logger.py

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/548

[Logger] Adapt with the new position channel

---

requirements.txt

Fixes https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/490 CI

Update OctoBot-Services requirement

---

octobot/backtesting/octobot_backtesting.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/592
requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/147

Rt tf in ta

---

octobot/cli.py
octobot/community/__init__.py
octobot/community/community_manager.py
octobot/community/errors_upload/__init__.py
octobot/community/errors_upload/error_model.py
octobot/community/errors_upload/errors_uploader.py
octobot/community/errors_upload/initializer.py
octobot/constants.py
requirements.txt
tests/unit_tests/community/errors_upload/__init__.py
tests/unit_tests/community/errors_upload/test_error_model.py
tests/unit_tests/community/errors_upload/test_errors_uploader.py
tests/unit_tests/community/errors_upload/test_initializer.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/196
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/198

[ErrorsUploader] register error uploader

---

octobot/community/errors_upload/error_model.py
tests/docker-entrypoint.sh
tests/unit_tests/community/errors_upload/test_error_model.py
tests/unit_tests/community/errors_upload/test_errors_uploader.py

linked to https://github.com/Drakkar-Software/Errors-Server/pull/4

[ErrorUpload] update error model

---

octobot/logger.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/613

Log porfolio as float

---

CHANGELOG.md
README.md
octobot/constants.py
requirements.txt

requires OctoBot-Trading 1.13.19

[Version] v0.4.0b15

---

octobot/logger.py
requirements.txt

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/656

Update logger to support trading channel updates

---

CHANGELOG.md
README.md
octobot/community/errors_upload/error_model.py
octobot/constants.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/708

release fixes

---

dev_requirements.txt
tests/unit_tests/community/test_community_feed.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/659

[Tests] migrate async fixtures

---

octobot/config/logging_config.ini
octobot/constants.py
octobot/logger.py

CI will pass after https://github.com/Drakkar-Software/OctoBot/pull/2003/commits

Reduce logs

---

octobot/community/authentication.py
octobot/community/feeds/community_mqtt_feed.py
octobot/community/graphql_requests.py
octobot/constants.py
tests/unit_tests/community/test_authentication.py
tests/unit_tests/community/test_community_mqtt_feed.py

req https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/680 for web UI

[Community] update for new backend

---

octobot/community/authentication.py
octobot/community/feeds/abstract_feed.py
octobot/community/feeds/community_mqtt_feed.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/266
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/727

handle invalid uuid

---

octobot/cli.py
octobot/commands.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/271
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/141

[Profiles] ignore bot version from imported profiles

---

CHANGELOG.md
README.md
octobot/community/authentication.py
octobot/community/community_user_account.py
octobot/constants.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/143
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/733

[Requirements] bump requirements

---

CHANGELOG.md
README.md
octobot/constants.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot/pull/2059

 Master merge

---

CHANGELOG.md
README.md
octobot/community/feeds/community_mqtt_feed.py
octobot/constants.py
octobot/strategy_optimizer/strategy_test_suite.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Evaluators/pull/187
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/749

Optimizer stop fix

---

octobot/octobot.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/283

[Clock] add clock synchronizer call

---

Dockerfile
docker/docker-entrypoint.sh
docker/efs.sh
docker/s3fs.sh

[Docker] Add efs

---

octobot/community/community_analysis.py
tests/unit_tests/community/test_community_data.py

requires https://github.com/Drakkar-Software/Metrics-Server/pull/19 to be deployed

[Metrics] use updated metrics endpoint

---

.github/workflows/docker.yml

Notify on dockerhub release

---

octobot/config/default_config.json
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/764

[Config] use "default" as default profile id

---

exchanges_tests/abstract_authenticated_exchange_tester.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/791

 [Exchange] migrate to RestExchange

---

exchanges_tests/__init__.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/805

[Requirements] bump

---

octobot/community/__init__.py
octobot/community/authentication.py
octobot/community/graphql_requests.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/809

push pf & trades history

---

octobot/automation/automation.py
requirements.txt
tests/functional_tests/automations/__init__.py
tests/functional_tests/automations/test_automation.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/152

[Automations] add tests

---

octobot/community/authentication.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/818

[Community] fix KeyError

---

octobot/automation/bases/abstract_trigger_event.py

uses https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/817

[Automations] add max_trigger_frequency

---

requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/144

[Requirements] bump services

---

octobot/limits.py
octobot/producers/exchange_producer.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/825
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/830
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/320
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/323

[Exchanges] use get_enabled_exchanges_names

---

octobot/constants.py
octobot/octobot.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/324
requires https://github.com/Drakkar-Software/trading-backend/pull/30
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/831
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/832

[ResourcesWatcher] allow file dump

---

octobot/community/authentication.py
octobot/configuration_manager.py
octobot/constants.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/325
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/153

io optimization

---

.gitpod.yml
README.md

Gives the Ability to Try out OctoBot on cloud with one click with automated setup.
- Updated .gitpod.yml file
*Gives Ability to Try out OctoBot on cloud with one click,user doesn't have to go through hassle of setting it up.It will automatically run all commands for the user.
*Helps to preview changes made in PR

Gitpodify OctoBot

---

exchanges_tests/abstract_authenticated_exchange_tester.py
exchanges_tests/abstract_authenticated_future_exchange_tester.py
exchanges_tests/test_ascendex.py
exchanges_tests/test_binance.py
exchanges_tests/test_bitget.py
exchanges_tests/test_bybit.py
exchanges_tests/test_bybit_futures.py
exchanges_tests/test_coinbasepro.py
exchanges_tests/test_hollaex.py
exchanges_tests/test_huobi.py
exchanges_tests/test_kucoin.py
exchanges_tests/test_kucoin_futures.py
exchanges_tests/test_okx.py
exchanges_tests/test_okx_futures.py
exchanges_tests/test_phemex.py
octobot/community/__init__.py
octobot/community/authentication.py
octobot/community/community_user_account.py
octobot/community/graphql_requests.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/849
requires https://github.com/Drakkar-Software/OctoBot/pull/2233

[Community] use upsert for history

---

octobot/community/errors_upload/error_model.py
octobot/task_manager.py

This PR includes fixes that make sure its compatible with python 3.8, 3.9 and 3.10

[Python] add support for multiple python versions

---

octobot/commands.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/334

[Profiles] add validation schema arg

---

octobot/octobot.py
octobot/storage/trading_metadata.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/855

[Metadata] skip unhandled contracts

---

octobot/constants.py
octobot/octobot_api.pxd
octobot/octobot_api.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2256

Strat designer

---

docker/efs.sh

Inspired by https://github.com/aws/efs-utils/issues/23 and https://docs.aws.amazon.com/efs/latest/ug/efs-mount-helper.html#efs-mount-helper-how
May fix #2266

[Docker][EFS] Try to fix instability by removing tls option

---

docker/efs.sh

https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/637

[Docker][EFS] Add watchdog

---

CHANGELOG.md
README.md
octobot/__init__.py
octobot/community/authentication.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/871

fix pf update error

---

octobot/config/profile_schema.json
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/346

[Profiles] add risk and complexity

---

exchanges_tests/abstract_authenticated_exchange_tester.py
exchanges_tests/test_coinbase.py

requires trading version with https://github.com/Drakkar-Software/OctoBot-Trading/pull/880
requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/916

[Tests] Coinbase advanced

---

octobot/logger.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/884

[Orders] add update_type to channel

---

CHANGELOG.md
README.md
octobot/__init__.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/156

[Version] v0.4.49

---

octobot/commands.py
octobot/constants.py

todo:
in deploy, replace existing url "latest" by "VERSION_PLACEHOLDER"

[Tentacles] allow multiplie urls

---

requirements.txt

requires https://github.com/Drakkar-Software/trading-backend/pull/37

[Requirements] bump trading_backend

---

CHANGELOG.md
README.md
octobot/__init__.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/932

[Version] v0.4.52

---

additional_tests/exchanges_tests/test_huobi.py
additional_tests/supabase_backend_tests/__init__.py
additional_tests/supabase_backend_tests/test_bot_elements.py
octobot/community/authentication.py
octobot/community/community_manager.py
octobot/community/models/__init__.py
octobot/community/models/community_user_account.py
octobot/community/models/formatters.py
octobot/community/supabase_backend/community_supabase_client.py
octobot/community/supabase_backend/enums.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/382

[Community] update profile config

---

requirements.txt

require https://github.com/Drakkar-Software/OctoBot-Trading/pull/952

[Requirements] bump trading

---

additional_tests/supabase_backend_tests/__init__.py
additional_tests/supabase_backend_tests/test_bot_elements.py
octobot/community/supabase_backend/community_supabase_client.py
octobot/community/supabase_backend/enums.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Services/pull/160

Community up

---

dev_requirements.txt
octobot/community/errors_upload/sentry_aiohttp_transport.py
tests/unit_tests/community/errors_upload/test_sentry_aiohttp_transport.py

[Sentry] add SentryAiohttpTransport tests

---

additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
additional_tests/exchanges_tests/test_ascendex.py
additional_tests/exchanges_tests/test_hollaex.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/959

[Trades] update exchange tests for exchange_trade_id

---

octobot/backtesting/octobot_backtesting.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/179
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/964
requires https://github.com/Drakkar-Software/Async-Channel/pull/112

[Backtesting] update for time channel

---

requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/394

[Requirements] bump commons

---

README.md

part 1: without gif update
requires https://github.com/Drakkar-Software/OctoBot/compare/readme_assets?expand=1

[Readme] refresh readme

---

README.md
requirements.txt

[Readme] add docs link

---

.github/workflows/main.yml
octobot/community/supabase_backend/community_supabase_client.py
octobot/community/supabase_backend/enums.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/402
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/982

[Community] update fetch_bot_profile_data

---

README.md

Preview available at https://github.com/Drakkar-Software/OctoBot/tree/feature/add-chatwoot

[Readme] Add chatwoot

---

octobot/community/supabase_backend/community_supabase_client.py
requirements.txt

does not fix anything but might help with logs

[Community] enable httpx loggers

---

octobot/community/supabase_backend/supabase_client.py

[Community] increase supabase timeout

---

additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1010

Fut order sze

---

additional_tests/exchanges_tests/test_binance_futures.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1037

[CCXT] update to 4.2.77

---

octobot/community/supabase_backend/enums.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1048

Compliancy

---

octobot/cli.py
octobot/community/models/strategy_data.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1058

use same Strategy profit as cloud

---

octobot/community/__init__.py
octobot/community/authentication.py
octobot/community/errors.py
octobot/community/feeds/__init__.py
octobot/community/feeds/abstract_feed.py
octobot/community/feeds/community_mqtt_feed.py
octobot/community/feeds/feed_factory.py
octobot/community/models/community_user_account.py
octobot/constants.py
requirements.txt
tests/unit_tests/community/test_authentication.py
tests/unit_tests/community/test_community_mqtt_feed.py
tests/unit_tests/community/test_community_supabase_feed.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/430
requres https://github.com/Drakkar-Software/OctoBot-Services/pull/173

commnity webhook

---

octobot/community/authentication.py
octobot/community/models/community_public_data.py
octobot/community/models/strategy_data.py
octobot/community/supabase_backend/community_supabase_client.py
octobot/constants.py
octobot/octobot.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/431
requires https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/pull/178

Prof update and index profiles

---

additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
additional_tests/exchanges_tests/test_ascendex.py
additional_tests/exchanges_tests/test_binance.py
additional_tests/exchanges_tests/test_binance_futures.py
additional_tests/exchanges_tests/test_bingx.py
additional_tests/exchanges_tests/test_bitget.py
additional_tests/exchanges_tests/test_bybit.py
additional_tests/exchanges_tests/test_bybit_futures.py
additional_tests/exchanges_tests/test_coinbase.py
additional_tests/exchanges_tests/test_coinex.py
additional_tests/exchanges_tests/test_cryptocom.py
additional_tests/exchanges_tests/test_hollaex.py
additional_tests/exchanges_tests/test_htx.py
additional_tests/exchanges_tests/test_kucoin.py
additional_tests/exchanges_tests/test_kucoin_futures.py
additional_tests/exchanges_tests/test_mexc.py
additional_tests/exchanges_tests/test_okx.py
additional_tests/exchanges_tests/test_okx_futures.py
additional_tests/exchanges_tests/test_phemex.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1070

[Exchanges] add get_cancelled_orders test

---

octobot/task_manager.py

[Logs] avoid Unclosed client session warning

---

octobot/cli.py
octobot/community/authentication.py
octobot/community/supabase_backend/community_supabase_client.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/440

[Community] add auth fetch

---

octobot/community/supabase_backend/community_supabase_client.py
octobot/community/supabase_backend/enums.py
requirements.txt

require https://github.com/Drakkar-Software/OctoBot-Commons/pull/444

[Community] add exchange_id

---

octobot/community/models/strategy_data.py

fixes "None" default in porfitability

[Community] handle None max values

---

additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
additional_tests/exchanges_tests/abstract_authenticated_future_exchange_tester.py
additional_tests/exchanges_tests/test_ascendex.py
additional_tests/exchanges_tests/test_binance.py
additional_tests/exchanges_tests/test_binance_futures.py
additional_tests/exchanges_tests/test_bingx.py
additional_tests/exchanges_tests/test_bitget.py
additional_tests/exchanges_tests/test_bitmart.py
additional_tests/exchanges_tests/test_bybit.py
additional_tests/exchanges_tests/test_bybit_futures.py
additional_tests/exchanges_tests/test_coinbase.py
additional_tests/exchanges_tests/test_coinex.py
additional_tests/exchanges_tests/test_cryptocom.py
additional_tests/exchanges_tests/test_gateio.py
additional_tests/exchanges_tests/test_hollaex.py
additional_tests/exchanges_tests/test_htx.py
additional_tests/exchanges_tests/test_kucoin.py
additional_tests/exchanges_tests/test_kucoin_futures.py
additional_tests/exchanges_tests/test_mexc.py
additional_tests/exchanges_tests/test_okx.py
additional_tests/exchanges_tests/test_okx_futures.py
additional_tests/exchanges_tests/test_phemex.py
octobot/community/authentication.py
octobot/community/models/formatters.py
octobot/community/supabase_backend/community_supabase_client.py
octobot/community/supabase_backend/enums.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1126
requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/447
requires https://github.com/Drakkar-Software/trading-backend/pull/69

[Community] add positions

---

additional_tests/exchanges_tests/abstract_authenticated_future_exchange_tester.py
additional_tests/exchanges_tests/test_kucoin_futures.py
requirements.txt

rquires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1154

[Tests] update exchange leverage tests

---

additional_tests/supabase_backend_tests/test_storage.py
octobot/community/supabase_backend/community_supabase_client.py
requirements.txt
tests/unit_tests/community/test_community_mqtt_feed.py

merge after worker up
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1155

WIP [Requirements] bump

---

additional_tests/exchanges_tests/__init__.py
additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
additional_tests/exchanges_tests/test_ascendex.py
additional_tests/exchanges_tests/test_binance.py
additional_tests/exchanges_tests/test_binance_futures.py
additional_tests/exchanges_tests/test_bingx.py
additional_tests/exchanges_tests/test_bitget.py
additional_tests/exchanges_tests/test_bitmart.py
additional_tests/exchanges_tests/test_bybit.py
additional_tests/exchanges_tests/test_bybit_futures.py
additional_tests/exchanges_tests/test_coinbase.py
additional_tests/exchanges_tests/test_coinex.py
additional_tests/exchanges_tests/test_cryptocom.py
additional_tests/exchanges_tests/test_gateio.py
additional_tests/exchanges_tests/test_hollaex.py
additional_tests/exchanges_tests/test_htx.py
additional_tests/exchanges_tests/test_kucoin.py
additional_tests/exchanges_tests/test_kucoin_futures.py
additional_tests/exchanges_tests/test_mexc.py
additional_tests/exchanges_tests/test_okx.py
additional_tests/exchanges_tests/test_okx_futures.py
additional_tests/exchanges_tests/test_phemex.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1431

[Tests] add test_api_key_ip_whitelist_error

---

additional_tests/exchanges_tests/test_binance.py
additional_tests/exchanges_tests/test_coinbase.py
additional_tests/exchanges_tests/test_kucoin.py
additional_tests/exchanges_tests/test_mexc.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1193

[Tests] update for quote market buy amount

---

requirements.txt

Do not merge yet
requires https://github.com/Drakkar-Software/trading-backend/pull/77
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1200

[Exchanges] update tests for ccxt update

---

CHANGELOG.md
README.md
octobot/__init__.py

requires https://github.com/Drakkar-Software/OctoBot/pull/2951
requires https://github.com/Drakkar-Software/OctoBot/pull/2939

[Version] v2.0.10

---

octobot/constants.py

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1502

[Community] remove clarity id

---

additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
additional_tests/exchanges_tests/abstract_authenticated_future_exchange_tester.py
additional_tests/exchanges_tests/test_binance.py
additional_tests/exchanges_tests/test_binance_futures.py
additional_tests/exchanges_tests/test_bingx.py
additional_tests/exchanges_tests/test_coinbase.py
additional_tests/exchanges_tests/test_kucoin.py
additional_tests/exchanges_tests/test_kucoin_futures.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1228

[Tests] add edit order tests

---

additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
additional_tests/exchanges_tests/abstract_authenticated_future_exchange_tester.py
additional_tests/exchanges_tests/test_ascendex.py
additional_tests/exchanges_tests/test_binance.py
additional_tests/exchanges_tests/test_binance_futures.py
additional_tests/exchanges_tests/test_bingx.py
additional_tests/exchanges_tests/test_bitget.py
additional_tests/exchanges_tests/test_bitmart.py
additional_tests/exchanges_tests/test_bybit.py
additional_tests/exchanges_tests/test_bybit_futures.py
additional_tests/exchanges_tests/test_coinbase.py
additional_tests/exchanges_tests/test_coinex.py
additional_tests/exchanges_tests/test_cryptocom.py
additional_tests/exchanges_tests/test_gateio.py
additional_tests/exchanges_tests/test_hollaex.py
additional_tests/exchanges_tests/test_htx.py
additional_tests/exchanges_tests/test_hyperliquid.py
additional_tests/exchanges_tests/test_kucoin.py
additional_tests/exchanges_tests/test_kucoin_futures.py
additional_tests/exchanges_tests/test_mexc.py
additional_tests/exchanges_tests/test_okx.py
additional_tests/exchanges_tests/test_okx_futures.py
additional_tests/exchanges_tests/test_phemex.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1524
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1233

[Tests] add test_get_max_orders_count

---

octobot/community/authentication.py
octobot/community/models/formatters.py
octobot/community/supabase_backend/community_supabase_client.py
octobot/community/supabase_backend/enums.py
requirements.txt
tests/unit_tests/community/test_community_supabase_client.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1249

[Community] add fetch_exchanges params

---

additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
octobot/community/models/formatters.py
octobot/community/supabase_backend/enums.py
requirements.txt
tests/unit_tests/trading_modes_tests/trading_mode_test_toolkit.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1266

[Orders] handle partially filled orders

---

octobot/community/supabase_backend/enums.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1285

Too many orders
