Drakkar-Software/OctoBot

- docs/install/windows/windows_installer.bat
In the command line 'copy default_config.json ../config.json' (line 34) Windows returns an error with the '/' because a '\\' is expected.
> [Installation] Error during installation on Window (#274)

- requirements.txt
- Remove tensorflow currently unused and python3.7 incompatible
> Remove tensorflow from requirements

- config/__init__.py
- tools/__init__.py
- Add error in logs when OctoBot is started with admin / sudo rights.
resolves #298
> Add error log when started with sudo

- .travis.yml
- If setup.py build script pass deployment is triggered without waiting for pytest result.
See https://travis-ci.org/Drakkar-Software/OctoBot/jobs/486100232
> Fix travis deployment without testing

- config/__init__.py
- evaluator/RealTime/realtime_evaluator.py
- evaluator/Strategies/strategies_evaluator.py
- trading/exchanges/exchange_dispatcher.py
- trading/exchanges/exchange_symbol_data.py
- trading/exchanges/rest_exchanges/rest_exchange.py
Prepare [market making tentacles](https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/31)
> Add order book and recent trades data for realtime evaluators

- interfaces/web/templates/backtesting.html
- interfaces/web/templates/tentacles.html
However, it doesn't work on generated config checkboxes, I don't understand why yet
> #681 Improved checkboxes design

- interfaces/trading_util.py
- octobot.py
- trading/exchanges/exchange_dispatcher.py
- trading/exchanges/exchange_exceptions.py
- trading/trader/modes/abstract_mode_decider.py
- trading/trader/orders_manager.py
- trading/trader/trader.py
Now logs order details on creation, try to download order when missing from database and if it still doesn't work, force trader resync.
order creation log:
Trader               Created order on binance: {'info': {'symbol': 'ADABTC', 'orderId': 83540271, 'clientOrderId': 'FSFAEA5S15Q4S54KI4', 'transactTime': 1550874781847, 'price': '0.00001169', 'origQty': '132.00000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'NEW', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'SELL'}, 'id': '83540271', 'timestamp': 1550874781847, 'datetime': '2019-02-22T22:33:01.847Z', 'lastTradeTimestamp': None, 'symbol': 'ADA/BTC', 'type': 'limit', 'side': 'sell', 'price': 1.169e-05, 'amount': 132.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 132.0, 'status': …
> #691 fixed order database desync when using websocket

- interfaces/web/static/js/common/cst.js
- interfaces/web/static/js/common/util.js
few currencies:
before:
after:
many currencies:
before:
after:
=> blue is less aggressive than red, therefore better as a first color
also fixed color picker algo to use all colors
> portfolio pie chart now start with blue

- trading/trader/orders_manager.py
Will now be easy to differenciate the 2 order managers per exchange when looking at logs
> added identifier to simulator order manager logs

- README.md
- config/__init__.py
- config/config_schema.json
- docs/CHANGELOG.md
Changelog for 0.3.3-beta
*Released date : April 18 2019*
#425 [Telemetry] Create telemetry deamon
#731 [Trader] Allow to start from the previous execution last move
#734 [Order] order_type is not consistent
#740 [RunInAsyncMainLoop] problem with exchange commands
#741 [WebInterface] add possibility to cancel orders
#747 [Backtesting] prepare for multiple data formats
#749 [Backtesting] impossible to display candles on specific timeframe from web interface
#750 [OrderCreator] error when computing order price
#751 [Backtesting] problem when saving config from web interface on backtesting
#752 [WebInterface] candles display bug
#756 [OrderManager] call_order_update_callback not called when exception in _update_order_status
#785 [Metrics] community metrics display
#792 …
> [Version] prepare 0.3.3

- interfaces/trading_util.py
- trading/trader/trader.py
This way on a config mistake the web interface still opens and if a simulator is activated, it can run also
> allowed bot start with mistakes in exchange config

- pre_requirements.txt
But urllib3 **1.25.1** is released.
> [CI] Fix setup.py dependencies error

- evaluator/Updaters/global_price_updater.py
now all symbols are updated at the same time when timeframes are refreshed, random delays are not affecting refresh time anymore
> #908 fixed timeframe update time

- interfaces/bots/telegram/bot.py
this doesn't work when update is null (possible if error on telegram notification)
> fix telegram

- interfaces/web/static/css/style.css
- interfaces/web/templates/layout.html
before
after
=> selected item is now slightly bolded
> improved navbar UI

- trading/exchanges/rest_exchanges/rest_exchange.py
- trading/trader/trader.py
Not a fan of the fix lines 236/237 but since Kraken doesn't send the order status at creation and immediatly after, I see no other option to keep complient with the bot requirements
> fix kraken orders

- .travis.yml
Problem was python 3.8 being used as new linux nightly default.
> Travis Linux CI fix

- interfaces/web/controllers/errors.py
- interfaces/web/static/js/common/common_handlers.js
- interfaces/web/static/js/common/util.js
- interfaces/web/templates/404.html
- interfaces/web/templates/500.html
Instead of default browser error pages:
when page not found:
when internal server error:
> #968 add not found and internal error handlers

- evaluator/Updaters/global_price_updater.py
the error:
problem: call finalize the backtesting is ended => if this last finalize triggers an order creation => error
> fix error on last backtesting tick if order creation

- tools/logger.py
matrix id in log is useless 99% of the time, display it at the end of the log
> display matrix ID at the end of matrix logs

- octobot/constants.py
You can now set env TENTACLES_URL_TAG = "latest" to install latest tentacles bundle (last pushed from OctoBot-Tentacles).
> [Tentacles] Add tentacles url environment var tag

- octobot/backtesting/octobot_backtesting.py
- octobot/factories/exchange_factory.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/196
> fix trading mode init

- Dockerfile
pip==20.2.3 doesn't seem to exist on arm64 (see [builder ci](https://travis-ci.com/github/Drakkar-Software/OctoBot-Builder/jobs/386631280))
> [Docker] Fix arm build

- octobot/community/community_manager.py
fixes https://github.com/Drakkar-Software/OctoBot-Launcher/issues/54 
> CommunityManager Exception when handling community registration: 'NoneType' object has no attribute 'get_name'
> handle no trading mode in community manager

- octobot/cli.py
Can be used, for example, to run an OctoBot in backtesting mode for model training purpose : 
```python
for backtesting_file in tqdm(BACKTESTING_FILES):
start_background_octobot_with_args(
backtesting=True,
simulate=False,
backtesting_files=[backtesting_file]
)
```
> [CLI] Add background_octobot_with_args function

- octobot/backtesting/abstract_backtesting_test.pxd
fixes 
ex in: https://github.com/Drakkar-Software/OctoBot-Tentacles/runs/2106148765?check_suite_focus=true#step:7:221
> [BacktestingTests] do not cythonize _handle_results to prevent warn

- .github/workflows/docker.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
Inspired from https://github.com/actions/create-release/issues/103
Should fix "Resource not accessible by integration" error when creating release or waiting for build status.
AUTH_TOKEN is a generated token from my account.
> [CI] Fix scoped GITHUB_ACTION usage

- octobot/__init__.pxd
- octobot/__init__.py
- octobot/cli.py
- octobot/constants.py
OctoBot should check after installing that OctoBot-Tentacles-Manager and OctoBot-Backtesting are installed instead of before processing dependencies.
- pip3 install OctoBot==0.4.0b6 with a fresh python environment
```bash
OctoBot requires OctoBot-Tentacles-Manager, you can install it using python3 -m pip install -U OctoBot-Tentacles-Manager
```
-  Pip or setup.py install without raising an exception
-  Raise when OctoBot is installed an run without OctoBot-Tentacles-Manager installed
> [Install] Fix exception when installing OctoBot from pip or setup.py

- .github/workflows/docker.yml
- Dockerfile
Based on https://github.com/Drakkar-Software/OctoBot/pull/1611
thanks to @gabriel-milan
> Disable rust compile on dockerfile

- .github/workflows/docker.yml
Goal:
Since armv7 build is more than 3h long, only build it on dev and tag pushes
Related to:
https://github.com/Drakkar-Software/OctoBot/pull/1612#issuecomment-807691963
> [Docker] build arm images only on dev or tag pushes

- octobot/commands.py
- requirements.txt
constants.OCTOBOT_FOLDER is the path to $(pwd)/octobot not $(pwd), the current bot installation path.
> [Commands] Fix bot install dir given to Tentacles-Manager

- octobot/cli.py
tentacles are checked after: they still will be installed if missing
> [Tentacles] avoid tentacles reinstall when profile can't be found

- requirements.txt
Inspired from https://github.com/pypa/setuptools/issues/3693 and https://github.com/numpy/numpy/issues/22623
> Fix cannot import name 'Log' from 'distutils.log'

- octobot/constants.py
- octobot/task_manager.py
adds a more convenient way to use the profiler
> [TaskManager] run backtesting in main thread when RUN_IN_MAIN_THREAD is set

- octobot/community/supabase_backend/community_supabase_client.py
- requirements.txt
requries https://github.com/Drakkar-Software/OctoBot-Trading/pull/993
> [Community] handle candles history fetch

- additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
- additional_tests/exchanges_tests/test_binance.py
- additional_tests/exchanges_tests/test_bingx.py
- additional_tests/exchanges_tests/test_coinbase.py
- additional_tests/exchanges_tests/test_kucoin.py
requires https://github.com/Drakkar-Software/OctoBot-Tentacles/pull/1396
> [Tests] add stop loss tests

- additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
- additional_tests/exchanges_tests/test_ascendex.py
- additional_tests/exchanges_tests/test_binance.py
- additional_tests/exchanges_tests/test_binance_futures.py
- additional_tests/exchanges_tests/test_bingx.py
- additional_tests/exchanges_tests/test_bitget.py
- additional_tests/exchanges_tests/test_bitmart.py
- additional_tests/exchanges_tests/test_bybit.py
- additional_tests/exchanges_tests/test_bybit_futures.py
- additional_tests/exchanges_tests/test_coinbase.py
- additional_tests/exchanges_tests/test_coinex.py
- additional_tests/exchanges_tests/test_cryptocom.py
- additional_tests/exchanges_tests/test_gateio.py
- additional_tests/exchanges_tests/test_hollaex.py
- additional_tests/exchanges_tests/test_htx.py
- additional_tests/exchanges_tests/test_kucoin.py
- additional_tests/exchanges_tests/test_kucoin_futures.py
- additional_tests/exchanges_tests/test_mexc.py
- additional_tests/exchanges_tests/test_okx.py
- additional_tests/exchanges_tests/test_okx_futures.py
- additional_tests/exchanges_tests/test_phemex.py
- octobot/community/models/formatters.py
- octobot/community/supabase_backend/enums.py
- requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1156
> Order tests

- additional_tests/exchanges_tests/abstract_authenticated_exchange_tester.py
- additional_tests/exchanges_tests/test_ascendex.py
- additional_tests/exchanges_tests/test_binance.py
- additional_tests/exchanges_tests/test_binance_futures.py
- additional_tests/exchanges_tests/test_bingx.py
- additional_tests/exchanges_tests/test_bitget.py
- additional_tests/exchanges_tests/test_bitmart.py
- additional_tests/exchanges_tests/test_bybit.py
- additional_tests/exchanges_tests/test_bybit_futures.py
- additional_tests/exchanges_tests/test_coinbase.py
- additional_tests/exchanges_tests/test_coinex.py
- additional_tests/exchanges_tests/test_cryptocom.py
- additional_tests/exchanges_tests/test_gateio.py
- additional_tests/exchanges_tests/test_hollaex.py
- additional_tests/exchanges_tests/test_htx.py
- additional_tests/exchanges_tests/test_kucoin.py
- additional_tests/exchanges_tests/test_kucoin_futures.py
- additional_tests/exchanges_tests/test_mexc.py
- additional_tests/exchanges_tests/test_okx.py
- additional_tests/exchanges_tests/test_okx_futures.py
- additional_tests/exchanges_tests/test_phemex.py
- requirements.txt
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1165
> [Tests] add tradable symbols test
